name: Cypress Tests
on:
  pull_request:
    branches:
    - main
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress.io
        uses: cypress-io/github-action@v6.3.0
        with:
          start: npm run dev
